# Generated by Django 3.0.1 on 2019-12-28 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_auto_20191228_1828'),
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avalicao',
            new_name='Avaliacao',
        ),
    ]
